### ISSUE TITLE
How to install tigre？

### ISSUE THREAD

**Issue by Love-Sunshine** [CERN/TIGRE#469]
I use this “python setup.py install” to install tigre, but the error occured, as follow:
nvcc fatal   : Unsupported gpu architecture 'compute_86'
error: command '/usr/local/cuda-11.0/bin/nvcc' failed with exit code 1
what can I do?
I try to add environment variable “  export TORCH_CUDA_ARCH_LIST="8.0"  ” to ~/.bashrc, but nothing help.

**Comment by AnderBiguri** [comment]
Hi!
There was a tiny mistake in the code for CUDA 11.0 specifically. I just updated master, it should be fixed now.

**Comment by Love-Sunshine** [comment]
sorry, I also have this question as follow:

**Comment by Love-Sunshine** [comment]
nvcc fatal : Unsupported gpu architecture 'compute_86'
error: command '/usr/local/cuda-11.0/bin/nvcc' failed with exit code 1

**Comment by AnderBiguri** [comment]
@Love-Sunshine TIGRE isntallation was just updated yesterday, did you use the latest version?

These errors of unsupported architecture are minor bugs in the installer, so I can fix easy if I know which version exactly you are using.

**Comment by Love-Sunshine** [comment]
Yes, I just download the latest version, but I still fail. The GPU uses NVIDIA TITAN Xp and NVIDIA RTX A5000, which are located on two devices respectively, and both devices' systems are Ubuntu 18.04. The version of CUDA is cuda_11.0.
I don't know if this information is sufficient.

**Comment by Love-Sunshine** [comment]
Sorry, I have encountered a new issue as follows:
ValueError: flag not understood, only ---no_pinned_memory accepted.
Can you help me? Thanks a lot.

**Comment by tsadakane** [comment]
https://github.com/CERN/TIGRE/blob/7510dff072a807816163703ca3fd0901d451c0df/Python/setup.py#L19-L26

Remove L. 23-26 from `setup.py` and retry.

**Comment by Love-Sunshine** [comment]
Thank you very much for your help. I am now able to install it. But I still encountered a small problem. When I use jupyter notebook to run "d03_generateData.py", "tigre.plotproj(projections)" and "tigre.plotproj(projections - noise_projections)" cannot display the drawn graph. How can I solve this problem?

**Comment by tsadakane** [comment]
Sorry, I don't use jupyter for tigre and I don't know much about it.

The `tigre.plotproj`  function draws the images on a plot area again and again. I'm not sure whether jupyter supprts that kind of displaying.
I guess you can run the script directly from the console:
```
python demos\d03_generateData.py
```

**Comment by Love-Sunshine** [comment]
Thanks a lot, I will try it again.
